#!/usr/bin/env bash
# Bootstrap the VeriForm repo on the NUS H200 cluster.
# Idempotent — safe to re-run on partial failures.
#
# Pre-reqs (you do these once, not the script):
#   - git clone -b migration/h200 git@github.com:rareone0602/VeriForm.git
#   - cd VeriForm
#   - gcloud SDK installed and authed (rareone0602@gmail.com), project
#     set to research-496610. The script bails if `gcloud auth list`
#     shows no active account.
#
# Usage:  bash scripts/bootstrap_h200.sh [--scratch /path/to/scratch]
#
# If --scratch is omitted, the script tries $SCRATCH, $WORK, then
# $HOME/scratch in that order, and creates the symlinks accordingly.

set -euo pipefail

# --- Argument parsing ---
SCRATCH_OVERRIDE=""
while [ $# -gt 0 ]; do
    case "$1" in
        --scratch) SCRATCH_OVERRIDE="$2"; shift 2 ;;
        --skip-hf) SKIP_HF=1; shift ;;
        --skip-data) SKIP_DATA=1; shift ;;
        --skip-lean) SKIP_LEAN=1; shift ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

# --- 1. Pre-flight: gcloud and bucket access ---
echo "=== [1/6] pre-flight checks ==="
command -v gcloud >/dev/null || { echo "gcloud not on PATH; install SDK first" >&2; exit 1; }
ACTIVE=$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | head -1)
[ -n "$ACTIVE" ] || { echo "no active gcloud account; run 'gcloud auth login'" >&2; exit 1; }
echo "  active gcloud: $ACTIVE"
PROJECT=$(gcloud config get-value project 2>/dev/null)
[ "$PROJECT" = "research-496610" ] || \
    { echo "project is $PROJECT, expected research-496610. fix with: gcloud config set project research-496610" >&2; exit 1; }
gcloud storage ls gs://veriform-faithformbench-2026/ >/dev/null 2>&1 \
    || { echo "cannot list gs://veriform-faithformbench-2026/ — check ACL" >&2; exit 1; }
echo "  bucket reachable."

# --- 2. Scratch layout ---
echo "=== [2/6] scratch + data symlinks ==="
if [ -n "$SCRATCH_OVERRIDE" ]; then
    SCRATCH="$SCRATCH_OVERRIDE"
elif [ -n "${SCRATCH:-}" ]; then
    : # use $SCRATCH from env
elif [ -n "${WORK:-}" ]; then
    SCRATCH="$WORK"
else
    SCRATCH="$HOME/scratch"
fi
mkdir -p "$SCRATCH/VeriForm"/{data,experiments,brokenmath_perturbations,hf_cache,vllm_tmp}
for d in data experiments brokenmath_perturbations; do
    if [ ! -e "$REPO/$d" ]; then
        ln -s "$SCRATCH/VeriForm/$d" "$REPO/$d"
        echo "  symlink: $REPO/$d -> $SCRATCH/VeriForm/$d"
    fi
done
export HF_HOME="$SCRATCH/VeriForm/hf_cache"
export TMPDIR="$SCRATCH/VeriForm/vllm_tmp"
export TRITON_CACHE_DIR="$TMPDIR/triton"
export VLLM_CACHE_ROOT="$TMPDIR/vllm"
mkdir -p "$TRITON_CACHE_DIR" "$VLLM_CACHE_ROOT"

# Write an env snippet the user can `source` in future shells
cat > .env.h200 <<EOF
# Generated by scripts/bootstrap_h200.sh on $(date -Is)
export HF_HOME="$HF_HOME"
export TMPDIR="$TMPDIR"
export TRITON_CACHE_DIR="$TRITON_CACHE_DIR"
export VLLM_CACHE_ROOT="$VLLM_CACHE_ROOT"
EOF
echo "  wrote .env.h200 (source it before launching jobs)"

# --- 3. Python venv ---
echo "=== [3/6] python venv ==="
if [ ! -d "$REPO/venv" ]; then
    python3 -m venv venv
fi
. venv/bin/activate
pip install --upgrade pip setuptools wheel >/dev/null
# Install requirements, preferring the cluster's wheel cache off /tmp
PIP_CACHE_DIR="$SCRATCH/VeriForm/pip-cache" pip install -r requirements.txt
pip install -e . >/dev/null
echo "  venv ready at $REPO/venv"

# --- 4. Lean toolchain + cache restore ---
if [ -z "${SKIP_LEAN:-}" ]; then
    echo "=== [4/6] Lean toolchain + .lake restore ==="
    if ! command -v elan >/dev/null && [ ! -x "$HOME/.elan/bin/elan" ]; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.elan-init.com | \
            sh -s -- -y --default-toolchain leanprover/lean4:v4.9.0-rc1
    fi
    export PATH="$HOME/.elan/bin:$PATH"
    LEAN_DIR="$REPO/src/veriform/proving/lean_server/lean"
    if [ ! -d "$LEAN_DIR/.lake" ]; then
        echo "  pulling Lean cache from GCS (~? GB compressed)..."
        gcloud storage cp gs://veriform-faithformbench-2026/lean-cache/lake-2026-05-17.tar.zst \
            "$SCRATCH/VeriForm/lake.tar.zst"
        tar --use-compress-program=zstd -xf "$SCRATCH/VeriForm/lake.tar.zst" -C "$LEAN_DIR"
        rm "$SCRATCH/VeriForm/lake.tar.zst"
    fi
    (cd "$LEAN_DIR" && lake build negate 2>&1 | tail -3)
    test -x "$LEAN_DIR/.lake/build/bin/negate" || { echo "negate exe missing after build" >&2; exit 1; }
    echo "  Lean OK: $($LEAN_DIR/.lake/build/bin/negate --version 2>/dev/null || echo 'built')"
else
    echo "=== [4/6] Lean: SKIPPED via --skip-lean ==="
fi

# --- 5. HF model prefetch ---
if [ -z "${SKIP_HF:-}" ]; then
    echo "=== [5/6] HF model prefetch (~25 GB, ~10-20 min) ==="
    # HF_TOKEN from .env if present (.env is gitignored; copy it manually)
    [ -f .env ] && set -a && . .env && set +a
    for model in \
        deepseek-ai/DeepSeek-Prover-V2-7B \
        FrenzyMath/Herald_translator \
        AI-MO/Kimina-Autoformalizer-7B \
        Goedel-LM/Goedel-Formalizer-V2-8B \
        stepfun-ai/StepFun-Formalizer-7B; do
        echo "  prefetching $model..."
        huggingface-cli download "$model" --quiet 2>&1 | tail -2 || \
            echo "    (skipped — check HF_TOKEN if private)"
    done
else
    echo "=== [5/6] HF: SKIPPED via --skip-hf ==="
fi

# --- 6. GCS data pull ---
if [ -z "${SKIP_DATA:-}" ]; then
    echo "=== [6/6] data pull from GCS ==="
    gcloud storage rsync -r gs://veriform-faithformbench-2026/data/ data/ 2>&1 | tail -3
    test -f data/parsed/unperturbed/dags.json || \
        { echo "dags.json missing after sync" >&2; exit 1; }
    echo "  data pulled. Pickle counts:"
    for method in regex brokenmath-soft brokenmath-medium brokenmath-hard; do
        for phase in formalized proved; do
            d="data/output/${method}-perturbed/${phase}"
            [ -d "$d" ] && \
                printf "    %-50s %6d pickles\n" "$d" "$(find "$d" -name '*.pkl' 2>/dev/null | wc -l)"
        done
    done
else
    echo "=== [6/6] data: SKIPPED via --skip-data ==="
fi

# --- 7. Smoke verification ---
echo "=== verification ==="
test -x "$REPO/src/veriform/proving/lean_server/lean/.lake/build/bin/negate" \
    && echo "  ✓ negate exe present"
test -f data/parsed/unperturbed/dags.json \
    && echo "  ✓ dags.json present"
test -d venv && echo "  ✓ venv present"
echo
echo "Bootstrap done. Source .env.h200 then run jobs via your cluster's"
echo "sbatch wrapper. See docs/H200_SETUP.md for architecture target."
